add error handeling in yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,7 +7,17 @@ before_install:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 
 script:
-  - docker build . -f Dockerfile -t $DOCKER_USERNAME/the_doctor:latest
+  - |
+    set -e
+    if ! docker build . -f Dockerfile -t $DOCKER_USERNAME/the_doctor:latest; then
+      echo "Docker build failed."
+      exit 1
+    fi
 
 after_success:
-  - docker push $DOCKER_USERNAME/the_doctor:latest
+  - |
+    set -e
+    if ! docker push $DOCKER_USERNAME/the_doctor:latest; then
+      echo "Docker push failed."
+      exit 1
+    fi
